### ISSUE TITLE
Outdated documentation (PageSpeed Insights Chrome extension)

### ISSUE THREAD

**Issue by leotm** [pagespeed/page-speed#336]
URL: https://developers.google.com/speed/docs/insights/EnableCompression#FAQ

Text: To determine if a proxy is the cause, you can use the [PageSpeed Insights Chrome extension](https://developers.google.com/speed/docs/insights/using_chrome) to examine the headers:

As we know and the link says, the extension has been depreciated.

**Comment by jeffkaufman** [comment]
Thanks!  That whole FAQ section is about debugging a problem that only happened with the extension version.  I'll update the docs to remove it.
